# -*- coding: utf-8 -*-
"""Siemens_Excel_trial_new.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XU13hJcHVstL7Ewu4oxf8XtPk7_Mhex9
"""

import openpyxl as op

workbook_salesforce = op.load_workbook("/Users/chiragnagpal/Documents/softwares/Python_programs/Siemens/final_try/2022-All BU-FC-WIN-Loss with ISO-2022-05-16-03-11-23.xlsx")

workbook_master = op.load_workbook("/Users/chiragnagpal/Documents/softwares/Python_programs/Siemens/final_try/All BU-FC-Win-Loss-2021-08-05-01-17-46-R-2.xlsm")

print(workbook_salesforce.sheetnames)
print(workbook_master.sheetnames)

sheet_sf = workbook_salesforce.worksheets[0] #accessing first sheet
sheet_master = workbook_master.worksheets[1] #accessing second sheet
maxrow = sheet_sf.max_row
print(maxrow)

dynamic_row = 2
array_index = 0
sfid_array = []
j = 1

while dynamic_row <= maxrow:
    cell_obj = sheet_sf.cell(row = dynamic_row, column=1)
    value = cell_obj.value

    if value not in sfid_array:
        sfid_array.append(value)
    else:
        new_val = value + "_" + str(j)
        sfid_array.append(new_val)
        j += 1

    dynamic_row += 1
    array_index += 1

new_dict = {}

for sfid in sfid_array:
    freq = sfid_array.count(sfid)
    if freq > 1:
        print(f"{sfid} : {freq}")
    new_dict[sfid] = freq

'''print()
print(new_dict)
print()
print(sfid_array)
print()
print(len(sfid_array))'''

# writing to master sheet

row_num = 2
for sf in sfid_array:
  cell = sheet_master.cell(row=row_num, column=1)
  #print(f"{sf} in Row : {row_num} and Col : 1")
  cell.value = sf
  row_num += 1

workbook_master.save("new_new_new_masterfile.xlsm")